#!/bin/bash

ls /home/user/skriptimine/praks4a/test
echo "Palun sisestage kataloogi nimi millena sa seda salvestada tahad"
read NAME
cp -r /home /home/user/skriptimine/praks4a/test/
tar -cvzf /home/user/skriptimine/praks4a/test/
echo "Sinu backup ülesanne on valmis. "
#Skripti lõpp
