#!/bin/bash

echo -n "Sisesta oma vanus: "
read vanus

if test $vanus -gt 0 -a $vanus -lt 11
then
echo "Oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
echo "Oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 64
then
echo "Oled täiskasvanu"
elif test $vanus -ge 64 -a $vanus -lt 117
then
echo "Oled seenior"
elif test $vanus -ge 118
then "Oled kõige vanem inimene"
else
echo "vigane sisend"
fi
