#!/bin/bash
#skripti algus

echo -n "Mis on A külje pikkus cm-tes? " #sisestatakse A külg
read A

echo -n "Mis on B külje pikkus cm-tes? " #sisestatakse B külg
read B

a_ruut=`echo "scale=2;($A^2)" | bc` #külje a väärtus ruudus
b_ruut=`echo "scale=2;($B^2)" | bc` #külje b väärtus ruudus
c_ruut=`echo "scale=2;($a_ruut+$b_ruut)" | bc` #külje c väärtus ruudus
c=`echo "scale=2;sqrt ($c_ruut)" | bc` 

echo "C külg on $c."

#Skripti lõpp

